logging:
  level:
    ROOT: debug
    jp.gmo.project: debug
  file:
    path: log

server:
  port: 8082

spring:
  application:
    name: project-service
  profiles:
    active: dev
  datasource:
     type: com.zaxxer.hikari.HikariDataSource
     url: jdbc:mysql://103.18.7.212:1247/db_webinternal?useUnicode=true&characterEncoding=utf8&useSSL=false
     username: runsystem-hcm
     password: Admi@1234
     hikari:
         auto-commit: false
         data-source-properties:
             cachePrepStmts: true
             prepStmtCacheSize: 250
             prepStmtCacheSqlLimit: 2048
             useServerPrepStmts: true
  jpa:
     database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
     database: MYSQL
     show-sql: true
     mapping-resources:
        sql/project-sql.xml
  jackson:
    serialization:
      write-dates-as-timestamps: false

gmo:
  url:
    getAccountInfo: http://localhost:8081/api/v1/user/get-account